# Generated by Django 5.0.6 on 2024-07-06 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consola', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consola')),
            ],
        ),
    ]
