# Generated by Django 5.0.6 on 2024-07-12 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_juegoindie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegoindie',
            name='desarrollador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario_Desarollador',
        ),
    ]
