# Generated by Django 5.0.6 on 2024-07-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_juegoindie_desarrollador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='caratula',
            field=models.ImageField(default='default_image.jpg', upload_to='img/caratula'),
        ),
    ]
