# Generated by Django 5.0.6 on 2024-07-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_juego_caratula'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegoindie',
            name='archivo',
            field=models.FileField(default='archivos_juegos/default_file.txt', upload_to='archivos_juegos/'),
        ),
    ]
