# Generated by Django 5.0.6 on 2024-07-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_juegoindie_desarrollador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='Descarga',
            field=models.FileField(default='archivos_juegos/default_file.txt', upload_to='Room/'),
        ),
    ]
