# Generated by Django 5.0.6 on 2024-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_juego_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(default='img/default_consola.jpg', upload_to='img/consolas'),
        ),
    ]
