# Generated by Django 5.0.6 on 2024-07-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_consola_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoIndieImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/indie')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.juegoindie')),
            ],
        ),
    ]
